catalog/urls.py
from django.conf.urls import url
# from django.urls import path
from . import views

app_name= 'catalog'

urlpatterns = [
    url(r'^$', views.index,name = "index"),
    url(r'^books/$', views.BookListView.as_view(), name='books_list'),
    url(r'^book_detail/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book_detail'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='add_book'),
    url(r'^book/(?P<pk>[-\w]+)/edit/$', views.BookEdit.as_view(), name='edit-book'),
    url(r'^book/(?P<pk>[-\w]+)/delete/$', views.BookDelete.as_view(), name='delete-book'),

]

locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from datetime import datetime, date
from django.db import models
from django.urls import reverse
from djchoices import ChoiceItem, DjangoChoices

class Book(models.Model):
    """
    Model representing a book
    """
    title = models.CharField(max_length=200)
    pub_date = models.DateField(default=date.today())
    number_of_pages = models.IntegerField(default=0)
    is_first_edition = models.BooleanField(default=True)

    Engineering = 'ER'
    Medical = 'ME'
    Art = 'AR'
    Psychology = 'PS'
    Field_Category_CHOICES = [
        (Engineering, 'Engineering'),
        (Medical, 'Medical'),
        (Art, 'Art'),
        (Psychology, 'Psychology'),
    ]
    category = models.CharField(
        max_length=2,
        choices=Field_Category_CHOICES,
        default=Engineering,
    )


    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('catalog:book_detail', args=[str(self.id)])


    def get_category_name(self):
        """
        Returns the url to access a particular book instance.
        """
        for choice in self.Field_Category_CHOICES:
            if choice[0] == self.category:
                return choice[1]

catalog/forms.py
from django import forms

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from . import models

def index(request):
    """
    View function for home page of site.
    """
    # Generate some of the main objects
    number=models.Book.objects.all().count()

    # Render the HTML template index.html
    return render(
        request,
        'catalog/index.html',
        context={'books_num':number},
    )

class BookListView(generic.ListView):
    model = models.Book
    template_name = 'catalog/book_list.html'

class AddBook(generic.ListView):
    model = models.Book
    template_name = 'catalog/add_book.html'

class BookDetailView(generic.DetailView):
    model = models.Book
    template_name='catalog/book_detail.html'

class BookCreate(generic.CreateView):
    model = models.Book
    fields = "__all__"
    # initial =
    template_name = 'catalog/add_book.html'

class BookEdit(generic.UpdateView):
    model = models.Book
    fields = "__all__"
    template_name = 'catalog/add_book.html'

class BookDelete(generic.DeleteView):
    model = models.Book
    template_name = 'catalog/delete_book.html'
    success_url = reverse_lazy('catalog:books_list')

catalog/templates/catalog/add_book.html
{% extends "catalog/base_generic.html" %}
{% block content %}

    <h1>Enter book infomation</h1><br><br><br>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/styles.css' %}">
</head>

<body>

  <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2">
              {% block sidebar %}
              <ul class="sidenav">
                  <br>
                  <br>
                  <br>
                  <li><a href="{% url 'catalog:index' %}"><h4>Home</h4></a></li>
                  <li><a href="{% url 'catalog:books_list' %}"><h4>All books</h4></a></li>
                  <li><a href="{% url 'catalog:add_book'%}"><h4>Add books</h4></a></li>
                  <li><a href="/admin/"> <h4>Admin Page</h4> </a></li>

              </ul>
             {% endblock %}
          </div>
          <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>
    <br><br>
    <h3><a href="{% url 'catalog:book_detail' book.id%}">{{ book.title }}</a></h3>
    <p> <strong>Books name: </strong> {{ book.title }}</p>
    <p> <strong>publication date: </strong> {{ book.pub_date }}</p>
    <p> <strong>number of pages: </strong> {{ book.number_of_pages }} </p>
    <p> <strong>is first edition: </strong> {{ book.is_first_edition }} </p>
    <p> <strong>category: </strong> {{ book.get_category_name }} </p>

    <hr>

       <form action="" method="post">

        {% csrf_token %}
        <table>
        {{ form }}
        </table>
           <a class="btn btn-primary" href="/catalog/book/{{ book.id }}/edit/">Edit</a>
           <a class="btn btn-primary" href="/catalog/book/{{ book.id }}/delete/">Delete</a>
    </form>



{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}"><h4>{{ book.title }}</h4></a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/delete_book.html
{% extends "catalog/base_generic.html" %}
{% block content %}

    <h1>Delete Book</h1><br>
    <p>Are you sure want to delete book  : {{ book.title }}  ?</p><br>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes,delete" />
    </form>

{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website </p>

<h2>Dynamic content</h2>

  <p>The library has the following records:</p>
  <ul>
    <li><strong>Number of available books:</strong> {{ books_num }}</li>
  </ul>

{% endblock %}